const TriviaQuestions= 
[ {question: "What is the largest planet in our solar system?",
  answer: "Jupiter"},
  {question: "Which country is commonly referred to as the Land of the Rising Sun?",
    answer: "Japan"},
  {question: "Who wrote the famous play 'Romeo and Juliet'?",
   answer: "Shakespeare"},
  {question: "What is the smallest bone in the human body?",
    answer: "The Stapes(in the ear)"},
  {question: "Which artist painted the Mona Lisa?",
  answer: "Leonardo da Vinci"},
  {question: "What is the capital city of Australia?",
  answer: "Canberra"},
  {question: "What is the chemical symbol for the element Gold?",
  answer: "Au"},
  {question: "In which year did the Titanic sink?",
  answer: "1912"},
  {question: "Who wrote the novel '1984'?",
  answer: "George Orwell"},
  {question: "Which planet is known as the Red Planet?",
  answer: "Mars"},
  {question: "What is the largest organ of the human body?",
  answer: "Skin (it puts the lotion)"},
  {question: "Who painted the ceiling of the Sistine Chapel?",
  answer: "Michelangelo"},
  {question: "What is the world's longest river?",
  answer: "The Nile River"},
  {question: "Which gas do plants absorb from the atmosphere?",
  answer: "Carbon dioxide (CO2)"},
  {question: "Who was the first person to step on the moon?",
  answer: "Neil Armstrong"},
  {question: "What is the largest ocean on Earth?",
  answer: "Pacific Ocean"},
  {question: "Who discovered penicillin?",
  answer: "Alexander Fleming"},
  {question: "What is the hardest natural substance on Earth?",
  answer: "Diamond"},
{question: "What is the only true flying mammal?",
  answer: "Bat"},
  {question: "What is the capital city of Spain?",
  answer: "Madrid"}];


export default TriviaQuestions